---
title: "Modeling plant stable isotopes using the 3PG forest growth model in R"
author: "Daniel M Griffith"
date: "April 12, 2018"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Installation

Install r3PG from GitHub using devtools.

```{r installation, message = FALSE, warning = FALSE, results = 'hide'}
install.packages("devtools", repos = "http://cran.us.r-project.org")
library(devtools)
install_github(repo = "griffithdan/r3PG")
library(r3PG)
```

## Load example dataset

```{r plots, echo=FALSE, fig.align = 'center', fig.width = 3, fig.height = 3}
data("example.config")
data("example.clim")
plot(example.clim[,1:3])
```

## Run example dataset

```{r example, echo=FALSE, fig.align = 'center', fig.width = 3, fig.height = 3}
output <- run_3pg(config = example.config, 
                  climate = example.clim, 
                  output = FALSE, 
                  python_indexing = FALSE)
head(output)
plot(output$D13CTissue ~ 1, type = "l") # add 1.5 to get gfrom wood to cellulose
```

## Compare species

```{r species, echo=FALSE, fig.align = 'center', fig.width = 3, fig.height = 3}
data("cfg.Pseudotsuga.menziesii")
data("cfg.Pinus.ponderosa")
pipo.run <- run_3pg(config = cfg.Pinus.ponderosa, 
                    climate = example.clim, 
                    output = FALSE, 
                    python_indexing = FALSE)
doug.run <- run_3pg(config = cfg.Pseudotsuga.menziesii, 
                    climate = example.clim, 
                    output = FALSE, 
                    python_indexing = FALSE)
plot(pipo.run$D13CTissue+1.5 ~ 1, type = "l", col = "dodgerblue")
lines(doug.run$D13CTissue+1.5 ~ 1, type = "l", col = "darkorange")
```

## Compare species at sites

```{r species, echo=FALSE, fig.align = 'center', fig.width = 3, fig.height = 3}
data("clim.Argentina")
data("clim.BritishColumbia")
data("clim.NorthCarolina")
data("clim.WesternOR")

cfg.Pinus.ponderosa$TimeRange
  cfg.Pinus.ponderosa$TimeRange$EndAge <- 25
  cfg.Pinus.ponderosa$TimeRange$EndYear <- 1975

pipo.Arg.run <- run_3pg(config = cfg.Pinus.ponderosa, 
                    climate = clim.Argentina, 
                    output = FALSE, 
                    python_indexing = FALSE)
pipo.WOR.run <- run_3pg(config = cfg.Pinus.ponderosa, 
                    climate = clim.WesternOR, 
                    output = FALSE, 
                    python_indexing = FALSE)
plot(pipo.Arg.run$D13CTissue+1.5 ~ 1, type = "l", col = "dodgerblue")
lines(pipo.WOR.run$D13CTissue+1.5 ~ 1, type = "l", col = "darkorange")
```



